spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://user:user@cluster0.un0kaso.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: InterviewPrep
      auto-index-creation: true

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/