spring:
  application:
    name: question-service
  data:
    mongodb:
      uri: mongodb+srv://user:user@cluster0.un0kaso.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: InterviewPrep
      auto-index-creation: true

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=
    key: AAIzaSyDdZpy3spAnFdI1ev0bgRU2f9XZppho-Vc

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/